# Generated by Django 5.0.4 on 2024-04-11 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0009_rename_tasktype_user_taskss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='taskss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.task'),
        ),
    ]
